local set = vim.keymap.set

set({ 'n', 't' }, '<C-b>', '<cmd>ToggleTerm<CR>')
set('v', 'p', '"_dP')
set({ 'n', 'v' }, 'd', '"_d')
set('i', '<C-v>', '<Esc>v')
set({ 'n', 'v' }, '<C-k>', '3k')
set({ 'n', 'v' }, '<C-j>', '3j')
set({ 'n', 'v' }, '<C-h>', 'b')
set({ 'n', 'v' }, '<C-l>', 'e')
set("v", "<Tab>", ">gv")
set("v", "<S-Tab>", "<gv")
set('n', '<Tab>', ':bnext<CR>')
set('n', '<S-Tab>', ':bprevious<CR>')
set('i', '<C-c>', '<Esc>')
set('i', '<C-k>', '<Up>')
set('i', '<C-j>', '<Down>')
set('i', '<C-h>', '<Left>')
set('i', '<C-l>', '<Right>')
set('i', '<C-d>', '<C-o>"_dw')
set('i', '<C-S-l>', "<delete>")
set('v', '{', 'c{}<Esc>hp')
set('v', '(', 'c()<Esc>hp')
set('v', '[', 'c[]<Esc>hp')
set('v', '"', 'c""<Esc>hp')
set('v', "'", "c''<Esc>hp")
set('v', '`', 'c``<Esc>hp')
set('v', '<', 'c<><Esc>hp')
set({ 'n', 'i' }, '<A-j>', '<CMD>m .1<CR>')
set({ 'n', 'i' }, '<A-k>', '<CMD>m .-2<CR>')
set("v", "<A-j>", ":m '>1<CR>gv=gv")
set("v", "<A-k>", ":m '<-2<CR>gv=gv")

-- del unused key map
vim.keymap.del('n', 'gc')
vim.keymap.del('n', 'gcc')
vim.keymap.del('x', "[%")
